flowchart TD
    subgraph Opción_1["Repositorio Único"]
      A1[Repo Fullstack]
      A1 --> B1[Carpeta /backend]
      A1 --> C1[Carpeta /frontend]
    end
    subgraph Opción_2["Repositorios Separados"]
      B2[Repo Backend]
      C2[Repo Frontend]
    end